#!/bin/bash

echo "========================================="
echo "Hugo Site Test Script"
echo "========================================="
echo ""
echo "Please install Hugo first with:"
echo "  sudo snap install hugo"
echo "  OR"
echo "  sudo apt install hugo"
echo ""
echo "Once Hugo is installed, run:"
echo "  hugo server -D"
echo ""
echo "The site will be available at:"
echo "  http://localhost:1313"
echo ""
echo "========================================="
echo "Configuration Summary:"
echo "========================================="
echo "Theme: Stack"
echo "Base URL: https://aaron.sachs.blog/"
echo "Content directories:"
echo "  - content/post/ (blog posts)"
echo "  - content/page/ (static pages)"
echo "  - content/archive/ (archived old posts)"
echo ""
echo "Key changes made:"
echo "  ✓ Migrated from Blackburn to Stack theme"
echo "  ✓ Updated configuration to hugo.yaml"
echo "  ✓ Archived old posts to content/archive/"
echo "  ✓ Created new welcome post"
echo "  ✓ Added search and archives pages"
echo ""